<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('city_mst')->truncate();
        DB::table('city_mst')->insert([
            [
                'id' => 1,
                'name' => 'An Giang',
                'code' => 89,
                'region' => 3,
                'slug' => 'an-giang',
                'type' => 1,
                'name_with_type' => 'Tỉnh An Giang',
                'latitude' => '10.5216',
                'longitude' => '105.1259',
                'order' => 1,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Bà Rịa - Vũng Tàu',
                'code' => 77,
                'region' => 3,
                'slug' => 'ba-ria-vung-tau',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bà Rịa - Vũng Tàu',
                'latitude' => '10.5417',
                'longitude' => '107.2430',
                'order' => 2,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Bắc Giang',
                'code' => 24,
                'region' => 3,
                'slug' => 'bac-giang',
                'latitude' => '21.2820',
                'longitude' => '106.1975',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bắc Giang',
                'order' => 3,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Bắc Kạn',
                'code' => 06,
                'region' => 3,
                'slug' => 'bac-kan',
                'latitude' => '22.1443',
                'longitude' => '105.8345',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bắc Kạn',
                'order' => 4,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Bạc Liêu',
                'code' => 95,
                'region' => 3,
                'slug' => 'bac-lieu',
                'latitude' => '9.2940',
                'longitude' => '105.7216',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bạc Liêu',
                'order' => 5,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Bắc Ninh',
                'code' => 27,
                'region' => 3,
                'slug' => 'bac-ninh',
                'latitude' => '21.1782',
                'longitude' => '106.0710',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bắc Ninh',
                'order' => 6,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Bến Tre',
                'code' => 83,
                'region' => 3,
                'slug' => 'ben-tre',
                'latitude' => '10.2434',
                'longitude' => '106.3756',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bến Tre',
                'order' => 7,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Bình Định',
                'code' => 52,
                'region' => 3,
                'slug' => 'binh-dinh',
                'latitude' => '14.1665',
                'longitude' => '108.9027',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bình Định',
                'order' => 8,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Bình Dương',
                'code' => 74,
                'region' => 3,
                'slug' => 'binh-duong',
                'latitude' => '11.3254',
                'longitude' => '106.4770',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bình Dương',
                'order' => 9,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Bình Phước',
                'code' => 70,
                'region' => 3,
                'slug' => 'binh-phuoc',
                'latitude' => '11.7512',
                'longitude' => '106.7235',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bình Phước',
                'order' => 10,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Bình Thuận',
                'code' => 60,
                'region' => 3,
                'slug' => 'binh-thuan',
                'latitude' => '11.0904',
                'longitude' => '108.0721',
                'type' => 1,
                'name_with_type' => 'Tỉnh Bình Thuận',
                'order' => 11,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Cà Mau',
                'code' => 96,
                'region' => 3,
                'slug' => 'ca-mau',
                'latitude' => '9.1527',
                'longitude' => '105.1961',
                'type' => 1,
                'name_with_type' => 'Tỉnh Cà Mau',
                'order' => 12,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Cần Thơ',
                'code' => 92,
                'region' => 3,
                'slug' => 'can-tho',
                'latitude' => '10.0452',
                'longitude' => '105.7469',
                'type' => 2,
                'name_with_type' => 'Thành phố Cần Thơ',
                'order' => 13,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Cao Bằng',
                'code' => 04,
                'region' => 3,
                'slug' => 'cao-bang',
                'latitude' => '22.6666',
                'longitude' => '106.2640',
                'type' => 1,
                'name_with_type' => 'Tỉnh Cao Bằng',
                'order' => 14,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Đà Nẵng',
                'code' => 48,
                'region' => 3,
                'slug' => 'da-nang',
                'latitude' => '16.0545',
                'longitude' => '108.0717',
                'type' => 2,
                'name_with_type' => 'Thành phố Đà Nẵng',
                'order' => 15,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Đắk Lắk',
                'code' => 66,
                'region' => 3,
                'slug' => 'dak-lak',
                'latitude' => '12.7100',
                'longitude' => '108.2378',
                'type' => 1,
                'name_with_type' => 'Tỉnh Đắk Lắk',
                'order' => 16,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Đắk Nông',
                'code' => 67,
                'region' => 3,
                'slug' => 'dak-nong',
                'latitude' => '12.2646',
                'longitude' => '107.6098',
                'type' => 1,
                'name_with_type' => 'Tỉnh Đắk Nông',
                'order' => 17,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Điện Biên',
                'code' => 11,
                'region' => 3,
                'slug' => 'dien-bien',
                'latitude' => '21.4064',
                'longitude' => '103.0322',
                'type' => 1,
                'name_with_type' => 'Tỉnh Điện Biên',
                'order' => 18,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Đồng Nai',
                'code' => 75,
                'region' => 3,
                'slug' => 'dong-nai',
                'latitude' => '11.0686',
                'longitude' => '107.1676',
                'type' => 1,
                'name_with_type' => 'Tỉnh Đồng Nai',
                'order' => 19,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Đồng Tháp',
                'code' => 87,
                'region' => 3,
                'slug' => 'dong-thap',
                'latitude' => '10.4938',
                'longitude' => '105.6882',
                'type' => 1,
                'name_with_type' => 'Tỉnh Đồng Tháp',
                'order' => 20,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Gia Lai',
                'code' => 64,
                'region' => 3,
                'slug' => 'gia-lai',
                'latitude' => '13.8079',
                'longitude' => '108.1094',
                'type' => 1,
                'name_with_type' => 'Tỉnh Gia Lai',
                'order' => 21,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Hà Giang',
                'code' => 64,
                'region' => 3,
                'slug' => 'ha-giang',
                'latitude' => '22.8026',
                'longitude' => '104.9784',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hà Giang',
                'order' => 22,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Hà Nam',
                'code' => 35,
                'region' => 3,
                'slug' => 'ha-nam',
                'latitude' => '20.5835',
                'longitude' => '105.9230',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hà Nam',
                'order' => 23,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Hà Nội',
                'code' => 1,
                'region' => 3,
                'slug' => 'ha-noi',
                'latitude' => '21.0278',
                'longitude' => '105.8342',
                'type' => 2,
                'name_with_type' => 'Thành phố Hà Nội',
                'order' => 24,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Hà Tĩnh',
                'code' => 42,
                'region' => 3,
                'slug' => 'ha-tinh',
                'latitude' => '18.3560',
                'longitude' => '105.8877',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hà Tĩnh',
                'order' => 25,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Hải Dương',
                'code' => 30,
                'region' => 3,
                'slug' => 'hai-duong',
                'latitude' => '20.9373',
                'longitude' => '106.3146',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hải Dương',
                'order' => 26,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Hải Phòng',
                'code' => 31,
                'region' => 3,
                'slug' => 'hai-phong',
                'latitude' => '20.8449',
                'longitude' => '106.6881',
                'type' => 2,
                'name_with_type' => 'Thành phố Hải Phòng',
                'order' => 27,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Hậu Giang',
                'code' => 93,
                'region' => 3,
                'slug' => 'hau-giang',
                'latitude' => '9.7579',
                'longitude' => '105.6413',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hậu Giang',
                'order' => 28,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Hòa Bình',
                'code' => 17,
                'region' => 3,
                'slug' => 'hoa-binh',
                'latitude' => '20.8275',
                'longitude' => '105.3391',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hoà Bình',
                'order' => 29,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Hưng Yên',
                'code' => 33,
                'region' => 3,
                'slug' => 'hung-yen',
                'latitude' => '20.6547',
                'longitude' => '106.0578',
                'type' => 1,
                'name_with_type' => 'Tỉnh Hưng Yên',
                'order' => 30,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Khánh Hòa',
                'code' => 56,
                'region' => 3,
                'slug' => 'khanh-hoa',
                'latitude' => '12.2585',
                'longitude' => '109.0526',
                'type' => 1,
                'name_with_type' => 'Tỉnh Khánh Hòa',
                'order' => 31,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'Kiên Giang',
                'code' => 91,
                'region' => 3,
                'slug' => 'kien-giang',
                'latitude' => '9.8250',
                'longitude' => '105.1259',
                'type' => 1,
                'name_with_type' => 'Tỉnh Kiên Giang',
                'order' => 32,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Kon Tum',
                'code' => 62,
                'region' => 3,
                'slug' => 'kon-tum',
                'latitude' => '14.3497',
                'longitude' => '108.0005',
                'type' => 1,
                'name_with_type' => 'Tỉnh Kon Tum',
                'order' => 33,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Lai Châu',
                'code' => 12,
                'region' => 3,
                'slug' => 'lai-chau',
                'latitude' => '22.3862',
                'longitude' => '103.4703',
                'type' => 1,
                'name_with_type' => 'Tỉnh Lai Châu',
                'order' => 34,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Lâm Đồng',
                'code' => 68,
                'region' => 3,
                'slug' => 'lam-dong',
                'latitude' => '11.5753',
                'longitude' => '108.1429',
                'type' => 1,
                'name_with_type' => 'Tỉnh Lâm Đồng',
                'order' => 35,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'Lạng Sơn',
                'code' => 20,
                'region' => 3,
                'slug' => 'lang-son',
                'latitude' => '21.8537',
                'longitude' => '106.7615',
                'type' => 1,
                'name_with_type' => 'Tỉnh Lạng Sơn',
                'order' => 36,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Lào Cai',
                'code' => 10,
                'region' => 3,
                'slug' => 'lao-cai',
                'latitude' => '22.4809',
                'longitude' => '103.9755',
                'type' => 1,
                'name_with_type' => 'Tỉnh Lào Cai',
                'order' => 37,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Long An',
                'code' => 80,
                'region' => 3,
                'slug' => 'long-an',
                'latitude' => '10.6956',
                'longitude' => '106.2431',
                'type' => 1,
                'name_with_type' => 'Tỉnh Long An',
                'order' => 38,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Nam Định',
                'code' => 36,
                'region' => 3,
                'slug' => 'nam-dinh',
                'latitude' => '20.4388',
                'longitude' => '106.1621',
                'type' => 1,
                'name_with_type' => 'Tỉnh Nam Định',
                'order' => 39,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'Nghệ An',
                'code' => 40,
                'region' => 3,
                'slug' => 'nghe-an',
                'latitude' => '19.2342',
                'longitude' => '104.9200',
                'type' => 1,
                'name_with_type' => 'Tỉnh Nghệ An',
                'order' => 40,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'Ninh Bình',
                'code' => 37,
                'region' => 3,
                'slug' => 'ninh-binh',
                'latitude' => '20.2506',
                'longitude' => '105.9745',
                'type' => 2,
                'name_with_type' => 'Thanh Phố Ninh Bình',
                'order' => 41,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'Ninh Thuận',
                'code' => 58,
                'region' => 3,
                'slug' => 'ninh-thuan',
                'latitude' => '11.6739',
                'longitude' => '108.8630',
                'type' => 1,
                'name_with_type' => 'Tỉnh Ninh Thuận',
                'order' => 42,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'Phú Thọ',
                'code' => 25,
                'region' => 3,
                'slug' => 'phu-tho',
                'latitude' => '21.4220',
                'longitude' => '105.2297',
                'type' => 1,
                'name_with_type' => 'Tỉnh Phú Thọ',
                'order' => 43,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Phú Yên',
                'code' => 54,
                'region' => 3,
                'slug' => 'phu-yen',
                'latitude' => '13.0882',
                'longitude' => '109.0929',
                'type' => 1,
                'name_with_type' => 'Tỉnh Phú Yên',
                'order' => 44,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Quảng Bình',
                'code' => 44,
                'region' => 3,
                'slug' => 'quang-binh',
                'latitude' => '17.6103',
                'longitude' => '106.3487',
                'type' => 1,
                'name_with_type' => 'Tỉnh Quảng Bình',
                'order' => 45,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'Quảng Nam',
                'code' => 49,
                'region' => 3,
                'slug' => 'quang-nam',
                'latitude' => '15.5394',
                'longitude' => '108.0191',
                'type' => 1,
                'name_with_type' => 'Tỉnh Quảng Nam',
                'order' => 46,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'Quảng Ngãi',
                'code' => 51,
                'region' => 3,
                'slug' => 'quang-ngai',
                'latitude' => '15.1214',
                'longitude' => '108.8044',
                'type' => 1,
                'name_with_type' => 'Tỉnh Quảng Ngãi',
                'order' => 47,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'Quảng Ninh',
                'code' => 22,
                'region' => 3,
                'slug' => 'quang-ninh',
                'latitude' => '21.0064',
                'longitude' => '107.2925',
                'type' => 1,
                'name_with_type' => 'Tỉnh Quảng Ninh',
                'order' => 48,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'Quảng Trị',
                'code' => 45,
                'region' => 3,
                'slug' => 'quang-tri',
                'latitude' => '16.7943',
                'longitude' => '106.9634',
                'type' => 1,
                'name_with_type' => 'Tỉnh Quảng Trị',
                'order' => 49,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'Sóc Trăng',
                'code' => 94,
                'region' => 3,
                'slug' => 'soc-trang',
                'latitude' => '9.6025',
                'longitude' => '105.9739',
                'type' => 1,
                'name_with_type' => 'Tỉnh Sóc Trăng',
                'order' => 50,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'Sơn La',
                'code' => 14,
                'region' => 3,
                'slug' => 'son-la',
                'latitude' => '21.3269',
                'longitude' => '103.9144',
                'type' => 1,
                'name_with_type' => 'Tỉnh Sơn La',
                'order' => 51,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'TP. Hồ Chí Minh',
                'code' => 79,
                'region' => 3,
                'slug' => 'tp-ho-chi-minh',
                'latitude' => '10.8231',
                'longitude' => '106.6297',
                'type' => 2,
                'name_with_type' => 'Thành phố Hồ Chí Minh',
                'order' => 52,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'Tây Ninh',
                'code' => 72,
                'region' => 3,
                'slug' => 'tay-ninh',
                'latitude' => '11.3352',
                'longitude' => '106.1099',
                'type' => 1,
                'name_with_type' => 'Tỉnh Tây Ninh',
                'order' => 53,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'Thái Bình',
                'code' => 34,
                'region' => 3,
                'slug' => 'thai-binh',
                'latitude' => '20.4463',
                'longitude' => '106.3366',
                'type' => 1,
                'name_with_type' => 'Tỉnh Thái Bình',
                'order' => 54,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'Thái Nguyên',
                'code' => 19,
                'region' => 3,
                'slug' => 'thai-nguyen',
                'latitude' => '21.5672',
                'longitude' => '105.8252',
                'type' => 1,
                'name_with_type' => 'Tỉnh Thái Nguyên',
                'order' => 55,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'Thanh Hóa',
                'code' => 38,
                'region' => 3,
                'slug' => 'thanh-hoa',
                'latitude' => '19.8067',
                'longitude' => '105.7852',
                'type' => 1,
                'name_with_type' => 'Tỉnh Thanh Hóa',
                'order' => 56,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => 'Thừa Thiên - Huế',
                'code' => 46,
                'region' => 3,
                'slug' => 'thua-thien-hue',
                'latitude' => '16.4637',
                'longitude' => '107.5909',
                'type' => 1,
                'name_with_type' => 'Tỉnh Thừa Thiên Huế',
                'order' => 57,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'Tiền Giang',
                'code' => 82,
                'region' => 3,
                'slug' => 'tien-giang',
                'latitude' => '10.4493',
                'longitude' => '106.3421',
                'type' => 1,
                'name_with_type' => 'Tỉnh Tiền Giang',
                'order' => 58,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'Trà Vinh',
                'code' => 84,
                'region' => 3,
                'slug' => 'tra-vinh',
                'latitude' => '9.9513',
                'longitude' => '106.3346',
                'type' => 1,
                'name_with_type' => 'Tỉnh Trà Vinh',
                'order' => 59,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'Tuyên Quang',
                'code' => 8,
                'region' => 3,
                'slug' => 'tuyen-quang',
                'latitude' => '21.7767',
                'longitude' => '105.2280',
                'type' => 1,
                'name_with_type' => 'Tỉnh Tuyên Quang',
                'order' => 60,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'Vĩnh Long',
                'code' => 86,
                'region' => 3,
                'slug' => 'vinh-long',
                'latitude' => '10.2396',
                'longitude' => '105.9572',
                'type' => 1,
                'name_with_type' => 'Tỉnh Vĩnh Long',
                'order' => 61,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'Vĩnh Phúc',
                'code' => 26,
                'region' => 3,
                'slug' => 'vinh-phuc',
                'latitude' => '21.3609',
                'longitude' => '105.5474',
                'type' => 1,
                'name_with_type' => 'Tỉnh Vĩnh Phúc',
                'order' => 62,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => 'Yên Bái',
                'code' => 15,
                'region' => 3,
                'slug' => 'yen-bai',
                'latitude' => '21.7168',
                'longitude' => '104.8986',
                'type' => 1,
                'name_with_type' => 'Tỉnh Yên Bái',
                'order' => 63,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        Schema::enableForeignKeyConstraints();
    }
}
