version: "3.7"

volumes:
    mysql_data: {}

services:
    mysql:
        image: mysql:8.0.32
        container_name: clinic-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - clinic-network

    app:
        build:
            args:
                user: nginx
                uid: 1000
            context: ./dockerfiles
            dockerfile: Dockerfile
        image: clinic
        container_name: clinic-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - clinic-network
#        entrypoint: ./dockerfiles/script/init.sh

    nginx:
        image: nginx:stable-alpine
        container_name: clinic-nginx
        restart: unless-stopped
        tty: true
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html

        depends_on:
            - app
            - mysql
        networks:
            - clinic-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: clinic-phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: unless-stopped
        ports:
            - ${PHP_MY_ADMIN_PORT}:80
        depends_on:
            - mysql
        networks:
            - clinic-network

networks:
    clinic-network:
        driver: bridge
        name: clinic-network
